# 垂直分片配置
spring:
  shardingsphere:
    datasource:
      # 配置真实数据源
      names: server-user,server-order
      # 配置server-user数据源
      server-user:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.101.117:3310/db_user?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
      # 配置server-order数据源
      server-order:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.101.117:3311/db_order?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
    rules:
      sharding:
        # 标准分片表配置（数据节点）
        tables:
          # 值由数据源名 + 表名组成，以小数点分隔
          t_user:
            actual-data-nodes: server-user.t_user
          t_order:
            actual-data-nodes: server-order.t_order
