server:
  port: 8080
spring:
  application:
    name: sharding-jdbc-demo
  profiles:
    active:
      - horizontal
  shardingsphere:
    mode:
      type: Memory
    # 打印SQl
    props:
      sql-show: true