# 水平分片配置
spring:
  shardingsphere:
    datasource:
      # 配置真实数据源
      names: server-order-3320,server-order-3321
      # 配置server-order-3320数据源
      server-order-3320:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.101.117:3320/db_order?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
      # 配置server-order-3321数据源
      server-order-3321:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.101.117:3321/db_order?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
    rules:
      sharding:
        # 标准分片表配置（数据节点）
        tables:
          # 值由数据源名 + 表名组成，以小数点分隔。多个表以逗号分隔，支持 inline 表达式。
          t_order:
            # 以下表达式解析结果：server-order-3320.t_order0,server-order-3320.t_order1,server-order-3321.t_order0,server-order-3321.t_order1
            #actual-data-nodes: server-order-332$->{0..1}.t_order$->{0..1}
            actual-data-nodes: server-order-332$->{0..1}.t_order0
            # 分库策略配置
            database-strategy:
              standard:
                # 分片列名称
                sharding-column: user_id
                # 分片算法名称
                sharding-algorithm-name: alg_inline_userid
        # 分片算法配置
        sharding-algorithms:
          alg_inline_userid:
            # 分片算法类型
            type: INLINE
            # 分片算法属性配置
            props:
              algorithm-expression: server-order-332$->{user_id % 2}